### PR TITLE
feat: add packet statistic api methods

### PR DESCRIPTION
**Pull request by kade-ddnkv**

### CODE REVIEW

**Comment by pirog-spb** [comment]
@kade-ddnkv Could you please provide example of API response with packet counters? Just to be sure that response is well formatted.

**Comment by kade-ddnkv** [comment]
An example of response:
http://localhost:8080/api/v1/packet_stats
{
    "RxArp": 2201,
    "RxIcmp": 0,
    "RxIcmp6": 36,
    "RxIp4": 11017,
    "RxIp6": 38,
    "RxTcp": 4457,
    "RxUdp": 6560,
    "RxOther": 2,
    "RxGtpEcho": 0,
    "RxGtpPdu": 0,
    "RxGtpOther": 0,
    "RxGtpUnexp": 0
}
I looked at other api calls and chose the style that was most common: UpperCamelCase. Should I have used snake_case? Or lowerCamelCase?

**Comment by pirog-spb** [comment]
If I'm not mistaken `xdp_stats` API has snake_case formatting. Adding corresponging annotaion to `UpfCounters` in case of new API to match snake_case would be nice.

**Comment by kade-ddnkv** [comment]
Like this?
{
    "rx_arp": 20,
    "rx_icmp": 0,
    "rx_icmp6": 10,
    "rx_ip4": 50,
    "rx_ip6": 11,
    "rx_tcp": 21,
    "rx_udp": 29,
    "rx_other": 1,
    "rx_gtp_echo": 0,
    "rx_gtp_pdu": 0,
    "rx_gtp_other": 0,
    "rx_gtp_unexp": 0
}

**Comment by pirog-spb** [comment]
Yep, exactly

пн, 18 сент. 2023 г., 13:19 kade-ddnkv ***@***.***>:

**Review by pirog-spb — APPROVED** [review]

**Pull request merged**
